version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: validator
    versions:
    - 13.5.2
  - dependency-name: react-modal
    versions:
    - 3.12.1
